build:
  base: /
  command: |
    apt-get update -y
    apt-get install -y postgresql-client libpq-dev
    pip install --upgrade pip
    pip install -r requirements.txt
    npm run build
  publish: .next
  environment:
    NODE_VERSION: 18.17.0
    NPM_VERSION: 9.6.7
    NETLIFY_USE_PYTHON: "true"
    PYTHON_VERSION: "3.9"
    SITE_NAME: "Digiclick Website"
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_NO_PYTHON_VERSION_WARNING: "1"
    PIP_NO_WARN_SCRIPT_LOCATION: "0"
    PIP_NO_CACHE_DIR: "off"

plugins:
  - package: "@netlify/plugin-nextjs"

redirects:
  - from: "/*"
    to: "/index.html"
    status: 200
