[build]
  base = "/"
  command = "./netlify.sh"
  publish = "out"
  ignore = "git diff --quiet HEAD^ HEAD -- . ':!node_modules'"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NETLIFY_USE_PYTHON = "true"
  PYTHON_VERSION = "3.9"
  SITE_NAME = "Digiclick Website"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"

[build.packages]
  apt = ["postgresql-client", "libpq-dev", "build-essential"]

[functions]
  node_bundler = "esbuild"

# These redirects are crucial for a Next.js application
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Handle 404 errors with custom 404 page
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# SPA fallback - this should be the last redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
