[build]
  command = "npm run build"
  publish = "out"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for images
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for CSS and JavaScript
[[headers]]
  for = "/*.{css,js}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for HTML and other dynamic content
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Ensure HTML files are served with correct content type
[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

# Prevent serving .txt files as pages
[[headers]]
  for = "/*.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    X-Robots-Tag = "noindex, nofollow"

# Enable HTTP/2 Server Push
[[headers]]
  for = "/*"
  [headers.values]
    Link = '''
    </styles/Home.module.css>; rel=preload; as=style,
    </styles/visual-effects.css>; rel=preload; as=style,
    </styles/navigation-enhancements.css>; rel=preload; as=style'''

# Redirect all traffic to HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Explicit redirects for main pages to ensure HTML is served
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact/index.html"
  status = 200

# Handle 404s for static site
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Enable brotli and gzip compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
